/* Generated by re2c 0.13.5 on Mon Sep 21 01:18:42 2015 */
#include "yoparser.h"

// #define YYPARSE_PARAM parm
// #define YYLEX_PARAM parm

// #define YY_DECL int yolex(YYSTYPE *lvalp)

#ifdef YYDEBUG
#undef YYDEBUG
#endif

#if 1
# define YYDEBUG(s, c) printf("state: %d char: %c\n", s, c)
#else
# define YYDEBUG(s, c)
#endif

// #include "yolang-y.h"

#define YYCTYPE   unsigned char
#define YYFILL(n) { if ((YYCURSOR + n) >= (YYLIMIT + YO_LEX_MAXFILL)) { return 0; } }
#define YYCURSOR  parser->cursor
#define YYLIMIT   parser->limit
#define YYMARKER  parser->marker

#if 0
#define YYGETSTATE()  parser->state
#define YYSETSTATE(s) parser->state = s
#define yych		 parser->ch
#define yyaccept	 parser->accept
#endif

#define YYGETCONDITION()  parser->state
#define YYSETCONDITION(c) parser->state = c

#define STATE(name)  YO_##name

/* emulate flex constructs */
#define BEGIN(state) YYSETSTATE(STATE(state))
#define YYSTATE      YYGETSTATE()
#define yytext       parser->text
#define yyleng       parser->textLen
#define yyless(x)    do { YYCURSOR = (YYCTYPE*)yytext + x; yyleng = (int)x; } while(0)
#define yymore()     goto yymore_restart

/* perform sanity check. If this message is triggered you should
   increase the YO_LEX_MAXFILL value in the yoparser.h file */
#define YYMAXFILL 12
#if YO_LEX_MAXFILL < YYMAXFILL
# error YO_LEX_MAXFILL should be greater than or equal to YYMAXFILL
#endif 

int yoLexIntRadix(YYSTYPE*, int radix, int skipEnd, void * parm, YYLTYPE*);
int yoLexFloat(YYSTYPE*, int skipEnd, void * parm, YYLTYPE*);
int yoLexName(YYSTYPE*, void * parm, YYLTYPE*);
int yoLexChar(YYSTYPE*, void * parm, YYLTYPE*);
void yoLexLineComment(void * parm, YYLTYPE*);
void yoLexMultiLineComment(void * parm, YYLTYPE*);
void yoLexNewLine(void * parm, YYLTYPE*);
int yoLexSingleQuotedString(YYSTYPE * elem, void * parm, YYLTYPE*);
int yoLexQuotedString(YYSTYPE * elem, void * parm, YYLTYPE*);
int yoLexInjectOpenBrace(YYSTYPE*, void * parm, YYLTYPE*);
int yoLexInjectCloseBrace(YYSTYPE*, void * parm, YYLTYPE*);
int yoLexOpenBrace(void * parm, YYLTYPE*);
int yoLexOpenBracket(void * parm, YYLTYPE*);
int yoLexCloseBracket(void * parm, YYLTYPE*);
void yoLexTrackRule(YYSTYPE*, void * parm, YYLTYPE*);

int yolex(YYSTYPE * parserElem, YYLTYPE * parserLoc, void * parm)
{
	YoParser * parser = (YoParser*)parm;
	// YYMARKER = YYCURSOR;
	
restart:
	yytext = YYCURSOR;

// yymore_restart:

	// -f option
	// YYCTYPE yych;
	// unsigned int yyaccept = 0;
	

{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if (YYGETCONDITION() < 1) {
		goto yyc_ST_INJECT;
	} else {
		goto yyc_ST_YOLANG;
	}
/* *********************************** */
yyc_ST_INJECT:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			120, 120,  88,  88,  88,  88,  88,  88, 
			 88,  88,   0,   0,   0,   0,   0,   0, 
			 64,  80,  80,  80,  80,  80,  80,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,   0,   0,   0,   0, 120, 
			  0,  80,  80,  80,  80,  80,  80,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,   0,   0,   0,   0,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
		};

		YYFILL(12);
		yych = *YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '#':
		case '$':
		case ',':
		case ';':
		case '?':
		case '[':
		case '\\':
		case ']':
		case '`':	goto yy73;
		case '\t':
		case ' ':	goto yy34;
		case '\n':	goto yy36;
		case '\r':	goto yy38;
		case '!':	goto yy2;
		case '"':	goto yy71;
		case '%':	goto yy18;
		case '&':	goto yy22;
		case '\'':	goto yy69;
		case '(':	goto yy61;
		case ')':	goto yy63;
		case '*':	goto yy14;
		case '+':	goto yy10;
		case '-':	goto yy12;
		case '.':	goto yy8;
		case '/':	goto yy16;
		case '0':	goto yy66;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy68;
		case ':':	goto yy32;
		case '<':	goto yy28;
		case '=':	goto yy30;
		case '>':	goto yy26;
		case '@':	goto yy6;
		case '^':	goto yy24;
		case 'a':	goto yy56;
		case 'b':	goto yy41;
		case 'c':	goto yy39;
		case 'd':	goto yy45;
		case 'e':	goto yy50;
		case 'f':	goto yy44;
		case 'g':	goto yy54;
		case 'i':	goto yy42;
		case 'l':	goto yy53;
		case 'm':	goto yy49;
		case 'n':	goto yy48;
		case 'r':	goto yy52;
		case 's':	goto yy46;
		case 't':	goto yy47;
		case 'u':	goto yy43;
		case 'v':	goto yy51;
		case 'w':	goto yy55;
		case '{':	goto yy57;
		case '|':	goto yy20;
		case '}':	goto yy59;
		case '~':	goto yy4;
		default:	goto yy65;
		}
yy2:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy418;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_NOT; }
yy4:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_TILDE; }
yy6:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_AT; }
yy8:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '.') goto yy412;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DOT; }
yy10:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '+') goto yy410;
		if (yych == '=') goto yy408;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_PLUS; }
yy12:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '-') goto yy406;
		if (yych == '=') goto yy404;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MINUS; }
yy14:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '*') goto yy398;
		if (yych == '=') goto yy400;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MUL; }
yy16:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '.') {
			if (yych == '*') goto yy392;
		} else {
			if (yych <= '/') goto yy394;
			if (yych == '=') goto yy396;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DIV; }
yy18:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy390;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MOD; }
yy20:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy388;
		if (yych == '|') goto yy386;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_OR; }
yy22:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '&') goto yy382;
		if (yych == '=') goto yy384;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_AND; }
yy24:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy380;
		if (yych == '^') goto yy378;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_XOR; }
yy26:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '<') goto yy27;
		if (yych <= '=') goto yy372;
		if (yych <= '>') goto yy374;
yy27:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_GT; }
yy28:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= ';') {
			if (yych == '-') goto yy368;
		} else {
			if (yych <= '<') goto yy366;
			if (yych <= '=') goto yy364;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LT; }
yy30:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy362;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_ASSIGN; }
yy32:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy360;
yy33:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexChar(parserElem, parm, parserLoc); }
yy34:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy359;
yy35:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ goto restart; }
yy36:
		++YYCURSOR;
yy37:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_NEWLINE; }
yy38:
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy357;
		goto yy37;
yy39:
		++YYCURSOR;
		switch ((yych = *YYCURSOR)) {
		case 'a':	goto yy322;
		case 'h':	goto yy323;
		case 'l':	goto yy324;
		case 'o':	goto yy325;
		default:	goto yy137;
		}
yy40:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexName(parserElem, parm, parserLoc); }
yy41:
		yych = *++YYCURSOR;
		if (yych <= 'q') {
			if (yych == 'o') goto yy309;
			goto yy137;
		} else {
			if (yych <= 'r') goto yy310;
			if (yych == 'y') goto yy311;
			goto yy137;
		}
yy42:
		yych = *++YYCURSOR;
		if (yych <= 'l') {
			if (yych == 'f') goto yy282;
			goto yy137;
		} else {
			if (yych <= 'm') goto yy284;
			if (yych <= 'n') goto yy285;
			goto yy137;
		}
yy43:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy263;
		goto yy137;
yy44:
		yych = *++YYCURSOR;
		if (yych <= 'l') {
			if (yych == 'a') goto yy234;
			if (yych <= 'k') goto yy137;
			goto yy235;
		} else {
			if (yych <= 'o') {
				if (yych <= 'n') goto yy137;
				goto yy236;
			} else {
				if (yych == 'u') goto yy237;
				goto yy137;
			}
		}
yy45:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy221;
		if (yych == 'o') goto yy222;
		goto yy137;
yy46:
		yych = *++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy196;
		case 'i':	goto yy197;
		case 't':	goto yy198;
		case 'w':	goto yy199;
		default:	goto yy137;
		}
yy47:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy188;
		if (yych == 'y') goto yy189;
		goto yy137;
yy48:
		yych = *++YYCURSOR;
		if (yych == 'u') goto yy184;
		goto yy137;
yy49:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy178;
		if (yych == 'u') goto yy179;
		goto yy137;
yy50:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy165;
		if (yych == 'x') goto yy166;
		goto yy137;
yy51:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy161;
		goto yy137;
yy52:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy155;
		goto yy137;
yy53:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy148;
		if (yych == 'o') goto yy149;
		goto yy137;
yy54:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy145;
		goto yy137;
yy55:
		yych = *++YYCURSOR;
		if (yych == 'h') goto yy140;
		goto yy137;
yy56:
		yych = *++YYCURSOR;
		if (yych == 's') goto yy138;
		goto yy137;
yy57:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexInjectOpenBrace(parserElem, parm, parserLoc); }
yy59:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexInjectCloseBrace(parserElem, parm, parserLoc); }
yy61:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexOpenBracket(parm, parserLoc); }
yy63:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexCloseBracket(parm, parserLoc); }
yy65:
		yych = *++YYCURSOR;
		goto yy137;
yy66:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == 'b') goto yy104;
		if (yych == 'x') goto yy105;
		goto yy75;
yy67:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 10, 0, parm, parserLoc); }
yy68:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy75;
yy69:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexSingleQuotedString(parserElem, parm, parserLoc); }
yy71:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexQuotedString(parserElem, parm, parserLoc); }
yy73:
		yych = *++YYCURSOR;
		goto yy33;
yy74:
		yyaccept = 0;
		YYMARKER = ++YYCURSOR;
		YYFILL(3);
		yych = *YYCURSOR;
yy75:
		if (yybm[0+yych] & 8) {
			goto yy74;
		}
		if (yych <= 'd') {
			if (yych <= '.') {
				if (yych <= '-') goto yy67;
			} else {
				if (yych == 'E') goto yy78;
				goto yy67;
			}
		} else {
			if (yych <= 'i') {
				if (yych <= 'e') goto yy78;
				if (yych <= 'h') goto yy67;
				goto yy79;
			} else {
				if (yych == 'u') goto yy80;
				goto yy67;
			}
		}
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy77;
		if (yych <= '9') goto yy102;
yy77:
		YYCURSOR = YYMARKER;
		if (yyaccept <= 1) {
			if (yyaccept <= 0) {
				goto yy67;
			} else {
				goto yy94;
			}
		} else {
			if (yyaccept <= 2) {
				goto yy108;
			} else {
				goto yy123;
			}
		}
yy78:
		yych = *++YYCURSOR;
		if (yych <= ',') {
			if (yych == '+') goto yy91;
			goto yy77;
		} else {
			if (yych <= '-') goto yy91;
			if (yych <= '/') goto yy77;
			if (yych <= '9') goto yy92;
			goto yy77;
		}
yy79:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy90;
		case '3':	goto yy89;
		case '6':	goto yy88;
		case '8':	goto yy81;
		default:	goto yy77;
		}
yy80:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy85;
		case '3':	goto yy84;
		case '6':	goto yy83;
		case '8':	goto yy81;
		default:	goto yy77;
		}
yy81:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 10, 2, parm, parserLoc); }
yy83:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy86;
		goto yy77;
yy84:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy86;
		goto yy77;
yy85:
		yych = *++YYCURSOR;
		if (yych != '6') goto yy77;
yy86:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 10, 3, parm, parserLoc); }
yy88:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy86;
		goto yy77;
yy89:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy86;
		goto yy77;
yy90:
		yych = *++YYCURSOR;
		if (yych == '6') goto yy86;
		goto yy77;
yy91:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy77;
		if (yych >= ':') goto yy77;
yy92:
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		YYFILL(3);
		yych = *YYCURSOR;
		if (yych <= '^') {
			if (yych <= '/') goto yy94;
			if (yych <= '9') goto yy92;
		} else {
			if (yych <= '_') goto yy92;
			if (yych == 'f') goto yy95;
		}
yy94:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexFloat(parserElem, 0, parm, parserLoc); }
yy95:
		yych = *++YYCURSOR;
		if (yych == '3') goto yy96;
		if (yych == '6') goto yy97;
		goto yy77;
yy96:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy100;
		goto yy77;
yy97:
		yych = *++YYCURSOR;
		if (yych != '4') goto yy77;
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexFloat(parserElem, 3, parm, parserLoc); }
yy100:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexFloat(parserElem, 3, parm, parserLoc); }
yy102:
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		YYFILL(3);
		yych = *YYCURSOR;
		if (yych <= '^') {
			if (yych <= '9') {
				if (yych <= '/') goto yy94;
				goto yy102;
			} else {
				if (yych == 'E') goto yy78;
				goto yy94;
			}
		} else {
			if (yych <= 'd') {
				if (yych <= '_') goto yy102;
				goto yy94;
			} else {
				if (yych <= 'e') goto yy78;
				if (yych <= 'f') goto yy95;
				goto yy94;
			}
		}
yy104:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy77;
		if (yych <= '1') goto yy121;
		goto yy77;
yy105:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy77;
			if (yych >= ':') goto yy77;
		} else {
			if (yych <= 'F') goto yy106;
			if (yych <= '`') goto yy77;
			if (yych >= 'g') goto yy77;
		}
yy106:
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		YYFILL(3);
		yych = *YYCURSOR;
		if (yybm[0+yych] & 16) {
			goto yy106;
		}
		if (yych == 'i') goto yy109;
		if (yych == 'u') goto yy110;
yy108:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 16, 0, parm, parserLoc); }
yy109:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy120;
		case '3':	goto yy119;
		case '6':	goto yy118;
		case '8':	goto yy111;
		default:	goto yy77;
		}
yy110:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy115;
		case '3':	goto yy114;
		case '6':	goto yy113;
		case '8':	goto yy111;
		default:	goto yy77;
		}
yy111:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 16, 2, parm, parserLoc); }
yy113:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy116;
		goto yy77;
yy114:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy116;
		goto yy77;
yy115:
		yych = *++YYCURSOR;
		if (yych != '6') goto yy77;
yy116:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 16, 3, parm, parserLoc); }
yy118:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy116;
		goto yy77;
yy119:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy116;
		goto yy77;
yy120:
		yych = *++YYCURSOR;
		if (yych == '6') goto yy116;
		goto yy77;
yy121:
		yyaccept = 3;
		YYMARKER = ++YYCURSOR;
		YYFILL(3);
		yych = *YYCURSOR;
		if (yybm[0+yych] & 32) {
			goto yy121;
		}
		if (yych == 'i') goto yy124;
		if (yych == 'u') goto yy125;
yy123:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 2, 0, parm, parserLoc); }
yy124:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy135;
		case '3':	goto yy134;
		case '6':	goto yy133;
		case '8':	goto yy126;
		default:	goto yy77;
		}
yy125:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy130;
		case '3':	goto yy129;
		case '6':	goto yy128;
		case '8':	goto yy126;
		default:	goto yy77;
		}
yy126:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 2, 2, parm, parserLoc); }
yy128:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy131;
		goto yy77;
yy129:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy131;
		goto yy77;
yy130:
		yych = *++YYCURSOR;
		if (yych != '6') goto yy77;
yy131:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 2, 3, parm, parserLoc); }
yy133:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy131;
		goto yy77;
yy134:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy131;
		goto yy77;
yy135:
		yych = *++YYCURSOR;
		if (yych == '6') goto yy131;
		goto yy77;
yy136:
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
yy137:
		if (yybm[0+yych] & 64) {
			goto yy136;
		}
		goto yy40;
yy138:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_AS; }
yy140:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_WHILE; }
yy145:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_GET; }
yy148:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy153;
		goto yy137;
yy149:
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'p') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LOOP; }
yy153:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LET; }
yy155:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_RETURN; }
yy161:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'd') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_VOID; }
yy165:
		yych = *++YYCURSOR;
		if (yych == 's') goto yy172;
		goto yy137;
yy166:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_EXTERN; }
yy172:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy137;
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '_') {
			if (yych <= '?') {
				if (yych <= '/') goto yy174;
				if (yych <= '9') goto yy136;
			} else {
				if (yych <= 'Z') goto yy136;
				if (yych >= '_') goto yy136;
			}
		} else {
			if (yych <= 'i') {
				if (yych <= '`') goto yy174;
				if (yych <= 'h') goto yy136;
				goto yy175;
			} else {
				if (yych <= 'z') goto yy136;
				if (yych >= 0x7F) goto yy136;
			}
		}
yy174:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_ELSE; }
yy175:
		yych = *++YYCURSOR;
		if (yych != 'f') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_ELSEIF; }
yy178:
		yych = *++YYCURSOR;
		if (yych == 'd') goto yy182;
		goto yy137;
yy179:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MUTABLE; }
yy182:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MODULE; }
yy184:
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_NULL; }
yy188:
		yych = *++YYCURSOR;
		if (yych == 'u') goto yy193;
		goto yy137;
yy189:
		yych = *++YYCURSOR;
		if (yych != 'p') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_TYPE; }
yy193:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_TRUE; }
yy196:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy219;
		goto yy137;
yy197:
		yych = *++YYCURSOR;
		if (yych == 'z') goto yy214;
		goto yy137;
yy198:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy205;
		goto yy137;
yy199:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_SWITCH; }
yy205:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy206;
		if (yych == 'u') goto yy207;
		goto yy137;
yy206:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy211;
		goto yy137;
yy207:
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_STRUCT; }
yy211:
		yych = *++YYCURSOR;
		if (yych != 'g') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_STRING; }
yy214:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'f') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_SIZEOF; }
yy219:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_SET; }
yy221:
		yych = *++YYCURSOR;
		if (yych == 'f') goto yy228;
		goto yy137;
yy222:
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'b') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy137;
yy226:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FLOAT64; }
yy228:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DEFAULT; }
yy234:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy250;
		goto yy137;
yy235:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy243;
		goto yy137;
yy236:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy241;
		goto yy137;
yy237:
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FUNC; }
yy241:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FOR; }
yy243:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '?') {
			if (yych <= '3') {
				if (yych <= '/') goto yy246;
				if (yych <= '2') goto yy136;
				goto yy247;
			} else {
				if (yych == '6') goto yy248;
				if (yych <= '9') goto yy136;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yy136;
				if (yych >= '_') goto yy136;
			} else {
				if (yych <= '`') goto yy246;
				if (yych <= 'z') goto yy136;
				if (yych >= 0x7F) goto yy136;
			}
		}
yy246:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FLOAT32; }
yy247:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy249;
		goto yy137;
yy248:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy226;
		goto yy137;
yy249:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy136;
		}
		goto yy246;
yy250:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy251;
		if (yych == 's') goto yy252;
		goto yy137;
yy251:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy255;
		goto yy137;
yy252:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FALSE; }
yy255:
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'g') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FALLTHROUGH; }
yy263:
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '9') {
			if (yych <= '3') {
				if (yych <= '0') {
					if (yych >= '0') goto yy136;
				} else {
					if (yych <= '1') goto yy269;
					if (yych <= '2') goto yy136;
					goto yy270;
				}
			} else {
				if (yych <= '6') {
					if (yych <= '5') goto yy136;
					goto yy271;
				} else {
					if (yych == '8') goto yy267;
					goto yy136;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych >= '@') goto yy136;
				} else {
					if (yych == '_') goto yy136;
				}
			} else {
				if (yych <= 'p') {
					if (yych <= 'o') goto yy136;
					goto yy272;
				} else {
					if (yych <= 'z') goto yy136;
					if (yych >= 0x7F) goto yy136;
				}
			}
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT; }
yy267:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT8; }
yy269:
		yych = *++YYCURSOR;
		if (yych == '6') goto yy280;
		goto yy137;
yy270:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy278;
		goto yy137;
yy271:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy276;
		goto yy137;
yy272:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINTPTR; }
yy276:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT64; }
yy278:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT32; }
yy280:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT16; }
yy282:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_IF; }
yy284:
		yych = *++YYCURSOR;
		if (yych == 'p') goto yy304;
		goto yy137;
yy285:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '_') {
			if (yych <= '?') {
				if (yych <= '/') goto yy286;
				if (yych <= '9') goto yy136;
			} else {
				if (yych <= 'Z') goto yy136;
				if (yych >= '_') goto yy136;
			}
		} else {
			if (yych <= 't') {
				if (yych <= '`') goto yy286;
				if (yych <= 's') goto yy136;
				goto yy287;
			} else {
				if (yych <= 'z') goto yy136;
				if (yych >= 0x7F) goto yy136;
			}
		}
yy286:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_IN; }
yy287:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '9') {
			if (yych <= '3') {
				if (yych <= '0') {
					if (yych >= '0') goto yy136;
				} else {
					if (yych <= '1') goto yy289;
					if (yych <= '2') goto yy136;
					goto yy290;
				}
			} else {
				if (yych <= '6') {
					if (yych <= '5') goto yy136;
					goto yy291;
				} else {
					if (yych == '8') goto yy292;
					goto yy136;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych >= '@') goto yy136;
				} else {
					if (yych == '_') goto yy136;
				}
			} else {
				if (yych <= 'p') {
					if (yych <= 'o') goto yy136;
					goto yy294;
				} else {
					if (yych <= 'z') goto yy136;
					if (yych >= 0x7F) goto yy136;
				}
			}
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INT; }
yy289:
		yych = *++YYCURSOR;
		if (yych == '6') goto yy302;
		goto yy137;
yy290:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy300;
		goto yy137;
yy291:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy298;
		goto yy137;
yy292:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INT8; }
yy294:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INTPTR; }
yy298:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INT64; }
yy300:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INT32; }
yy302:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INT16; }
yy304:
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_IMPORT; }
yy309:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy319;
		goto yy137;
yy310:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy315;
		goto yy137;
yy311:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT8; }
yy315:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'k') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_BREAK; }
yy319:
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_BOOL; }
yy322:
		yych = *++YYCURSOR;
		if (yych <= 'r') goto yy137;
		if (yych <= 's') goto yy350;
		if (yych <= 't') goto yy351;
		goto yy137;
yy323:
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy345;
		goto yy137;
yy324:
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy341;
		goto yy137;
yy325:
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy137;
		yych = *++YYCURSOR;
		if (yych <= 'r') goto yy137;
		if (yych <= 's') goto yy327;
		if (yych <= 't') goto yy328;
		goto yy137;
yy327:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy339;
		goto yy137;
yy328:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy330;
		if (yych != 'r') goto yy137;
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy335;
		goto yy137;
yy330:
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CONTINUE; }
yy335:
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CONTRACT; }
yy339:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CONST; }
yy341:
		yych = *++YYCURSOR;
		if (yych != 's') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 's') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CLASS; }
yy345:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy346;
		if (yych == 'r') goto yy348;
		goto yy137;
yy346:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CHAN; }
yy348:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT8; }
yy350:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy355;
		goto yy137;
yy351:
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy137;
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy137;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CATCH; }
yy355:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy136;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CASE; }
yy357:
		yych = *++YYCURSOR;
		goto yy37;
yy358:
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
yy359:
		if (yybm[0+yych] & 128) {
			goto yy358;
		}
		goto yy35;
yy360:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DECL_ASSIGN; }
yy362:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_EQ; }
yy364:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LE; }
yy366:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy370;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LSH; }
yy368:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CHAN_ACCESS; }
yy370:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LSH_ASSIGN; }
yy372:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_GE; }
yy374:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy376;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_RSH; }
yy376:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_RSH_ASSIGN; }
yy378:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_XORXOR; }
yy380:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_XOR_ASSIGN; }
yy382:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_ANDAND; }
yy384:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_AND_ASSIGN; }
yy386:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_OROR; }
yy388:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_OR_ASSIGN; }
yy390:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MOD_ASSIGN; }
yy392:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ yoLexMultiLineComment(parm, parserLoc); goto restart; }
yy394:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ yoLexLineComment(parm, parserLoc); goto restart; }
yy396:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DIV_ASSIGN; }
yy398:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy402;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_POW; }
yy400:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MUL_ASSIGN; }
yy402:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_POW_ASSIGN; }
yy404:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MINUS_ASSIGN; }
yy406:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DEC; }
yy408:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_PLUS_ASSIGN; }
yy410:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INC; }
yy412:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '.') goto yy416;
		if (yych == '=') goto yy414;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CONCAT; }
yy414:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CONCAT_ASSIGN; }
yy416:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DOTDOTDOT; }
yy418:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_NE; }
	}
/* *********************************** */
yyc_ST_YOLANG:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			120, 120,  88,  88,  88,  88,  88,  88, 
			 88,  88,   0,   0,   0,   0,   0,   0, 
			 64,  80,  80,  80,  80,  80,  80,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,   0,   0,   0,   0, 120, 
			  0,  80,  80,  80,  80,  80,  80,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,   0,   0,   0,   0,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
		};
		YYFILL(12);
		yych = *YYCURSOR;
		switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '#':
		case '$':
		case ',':
		case ';':
		case '?':
		case '[':
		case '\\':
		case ']':
		case '`':	goto yy491;
		case '\t':
		case ' ':	goto yy454;
		case '\n':	goto yy456;
		case '\r':	goto yy458;
		case '!':	goto yy422;
		case '"':	goto yy489;
		case '%':	goto yy438;
		case '&':	goto yy442;
		case '\'':	goto yy487;
		case '(':	goto yy479;
		case ')':
		case '}':	goto yy481;
		case '*':	goto yy434;
		case '+':	goto yy430;
		case '-':	goto yy432;
		case '.':	goto yy428;
		case '/':	goto yy436;
		case '0':	goto yy484;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy486;
		case ':':	goto yy452;
		case '<':	goto yy448;
		case '=':	goto yy450;
		case '>':	goto yy446;
		case '@':	goto yy426;
		case '^':	goto yy444;
		case 'a':	goto yy476;
		case 'b':	goto yy461;
		case 'c':	goto yy459;
		case 'd':	goto yy465;
		case 'e':	goto yy470;
		case 'f':	goto yy464;
		case 'g':	goto yy474;
		case 'i':	goto yy462;
		case 'l':	goto yy473;
		case 'm':	goto yy469;
		case 'n':	goto yy468;
		case 'r':	goto yy472;
		case 's':	goto yy466;
		case 't':	goto yy467;
		case 'u':	goto yy463;
		case 'v':	goto yy471;
		case 'w':	goto yy475;
		case '{':	goto yy477;
		case '|':	goto yy440;
		case '~':	goto yy424;
		default:	goto yy483;
		}
yy422:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy836;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_NOT; }
yy424:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_TILDE; }
yy426:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_AT; }
yy428:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '.') goto yy830;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DOT; }
yy430:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '+') goto yy828;
		if (yych == '=') goto yy826;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_PLUS; }
yy432:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '-') goto yy824;
		if (yych == '=') goto yy822;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MINUS; }
yy434:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '*') goto yy816;
		if (yych == '=') goto yy818;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MUL; }
yy436:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '.') {
			if (yych == '*') goto yy810;
		} else {
			if (yych <= '/') goto yy812;
			if (yych == '=') goto yy814;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DIV; }
yy438:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy808;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MOD; }
yy440:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy806;
		if (yych == '|') goto yy804;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_OR; }
yy442:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '&') goto yy800;
		if (yych == '=') goto yy802;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_AND; }
yy444:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy798;
		if (yych == '^') goto yy796;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_XOR; }
yy446:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '<') goto yy447;
		if (yych <= '=') goto yy790;
		if (yych <= '>') goto yy792;
yy447:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_GT; }
yy448:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= ';') {
			if (yych == '-') goto yy786;
		} else {
			if (yych <= '<') goto yy784;
			if (yych <= '=') goto yy782;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LT; }
yy450:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy780;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_ASSIGN; }
yy452:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy778;
yy453:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexChar(parserElem, parm, parserLoc); }
yy454:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy777;
yy455:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ goto restart; }
yy456:
		++YYCURSOR;
yy457:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_NEWLINE; }
yy458:
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy775;
		goto yy457;
yy459:
		++YYCURSOR;
		switch ((yych = *YYCURSOR)) {
		case 'a':	goto yy740;
		case 'h':	goto yy741;
		case 'l':	goto yy742;
		case 'o':	goto yy743;
		default:	goto yy555;
		}
yy460:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexName(parserElem, parm, parserLoc); }
yy461:
		yych = *++YYCURSOR;
		if (yych <= 'q') {
			if (yych == 'o') goto yy727;
			goto yy555;
		} else {
			if (yych <= 'r') goto yy728;
			if (yych == 'y') goto yy729;
			goto yy555;
		}
yy462:
		yych = *++YYCURSOR;
		if (yych <= 'l') {
			if (yych == 'f') goto yy700;
			goto yy555;
		} else {
			if (yych <= 'm') goto yy702;
			if (yych <= 'n') goto yy703;
			goto yy555;
		}
yy463:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy681;
		goto yy555;
yy464:
		yych = *++YYCURSOR;
		if (yych <= 'l') {
			if (yych == 'a') goto yy652;
			if (yych <= 'k') goto yy555;
			goto yy653;
		} else {
			if (yych <= 'o') {
				if (yych <= 'n') goto yy555;
				goto yy654;
			} else {
				if (yych == 'u') goto yy655;
				goto yy555;
			}
		}
yy465:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy639;
		if (yych == 'o') goto yy640;
		goto yy555;
yy466:
		yych = *++YYCURSOR;
		switch (yych) {
		case 'e':	goto yy614;
		case 'i':	goto yy615;
		case 't':	goto yy616;
		case 'w':	goto yy617;
		default:	goto yy555;
		}
yy467:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy606;
		if (yych == 'y') goto yy607;
		goto yy555;
yy468:
		yych = *++YYCURSOR;
		if (yych == 'u') goto yy602;
		goto yy555;
yy469:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy596;
		if (yych == 'u') goto yy597;
		goto yy555;
yy470:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy583;
		if (yych == 'x') goto yy584;
		goto yy555;
yy471:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy579;
		goto yy555;
yy472:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy573;
		goto yy555;
yy473:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy566;
		if (yych == 'o') goto yy567;
		goto yy555;
yy474:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy563;
		goto yy555;
yy475:
		yych = *++YYCURSOR;
		if (yych == 'h') goto yy558;
		goto yy555;
yy476:
		yych = *++YYCURSOR;
		if (yych == 's') goto yy556;
		goto yy555;
yy477:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexOpenBrace(parm, parserLoc); }
yy479:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexOpenBracket(parm, parserLoc); }
yy481:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexCloseBracket(parm, parserLoc); }
yy483:
		yych = *++YYCURSOR;
		goto yy555;
yy484:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == 'b') goto yy522;
		if (yych == 'x') goto yy523;
		goto yy493;
yy485:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 10, 0, parm, parserLoc); }
yy486:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy493;
yy487:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexSingleQuotedString(parserElem, parm, parserLoc); }
yy489:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexQuotedString(parserElem, parm, parserLoc); }
yy491:
		yych = *++YYCURSOR;
		goto yy453;
yy492:
		yyaccept = 0;
		YYMARKER = ++YYCURSOR;
		YYFILL(3);
		yych = *YYCURSOR;
yy493:
		if (yybm[0+yych] & 8) {
			goto yy492;
		}
		if (yych <= 'd') {
			if (yych <= '.') {
				if (yych <= '-') goto yy485;
			} else {
				if (yych == 'E') goto yy496;
				goto yy485;
			}
		} else {
			if (yych <= 'i') {
				if (yych <= 'e') goto yy496;
				if (yych <= 'h') goto yy485;
				goto yy497;
			} else {
				if (yych == 'u') goto yy498;
				goto yy485;
			}
		}
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy495;
		if (yych <= '9') goto yy520;
yy495:
		YYCURSOR = YYMARKER;
		if (yyaccept <= 1) {
			if (yyaccept <= 0) {
				goto yy485;
			} else {
				goto yy512;
			}
		} else {
			if (yyaccept <= 2) {
				goto yy526;
			} else {
				goto yy541;
			}
		}
yy496:
		yych = *++YYCURSOR;
		if (yych <= ',') {
			if (yych == '+') goto yy509;
			goto yy495;
		} else {
			if (yych <= '-') goto yy509;
			if (yych <= '/') goto yy495;
			if (yych <= '9') goto yy510;
			goto yy495;
		}
yy497:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy508;
		case '3':	goto yy507;
		case '6':	goto yy506;
		case '8':	goto yy499;
		default:	goto yy495;
		}
yy498:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy503;
		case '3':	goto yy502;
		case '6':	goto yy501;
		case '8':	goto yy499;
		default:	goto yy495;
		}
yy499:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 10, 2, parm, parserLoc); }
yy501:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy504;
		goto yy495;
yy502:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy504;
		goto yy495;
yy503:
		yych = *++YYCURSOR;
		if (yych != '6') goto yy495;
yy504:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 10, 3, parm, parserLoc); }
yy506:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy504;
		goto yy495;
yy507:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy504;
		goto yy495;
yy508:
		yych = *++YYCURSOR;
		if (yych == '6') goto yy504;
		goto yy495;
yy509:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy495;
		if (yych >= ':') goto yy495;
yy510:
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		YYFILL(3);
		yych = *YYCURSOR;
		if (yych <= '^') {
			if (yych <= '/') goto yy512;
			if (yych <= '9') goto yy510;
		} else {
			if (yych <= '_') goto yy510;
			if (yych == 'f') goto yy513;
		}
yy512:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexFloat(parserElem, 0, parm, parserLoc); }
yy513:
		yych = *++YYCURSOR;
		if (yych == '3') goto yy514;
		if (yych == '6') goto yy515;
		goto yy495;
yy514:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy518;
		goto yy495;
yy515:
		yych = *++YYCURSOR;
		if (yych != '4') goto yy495;
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexFloat(parserElem, 3, parm, parserLoc); }
yy518:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexFloat(parserElem, 3, parm, parserLoc); }
yy520:
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		YYFILL(3);
		yych = *YYCURSOR;
		if (yych <= '^') {
			if (yych <= '9') {
				if (yych <= '/') goto yy512;
				goto yy520;
			} else {
				if (yych == 'E') goto yy496;
				goto yy512;
			}
		} else {
			if (yych <= 'd') {
				if (yych <= '_') goto yy520;
				goto yy512;
			} else {
				if (yych <= 'e') goto yy496;
				if (yych <= 'f') goto yy513;
				goto yy512;
			}
		}
yy522:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy495;
		if (yych <= '1') goto yy539;
		goto yy495;
yy523:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy495;
			if (yych >= ':') goto yy495;
		} else {
			if (yych <= 'F') goto yy524;
			if (yych <= '`') goto yy495;
			if (yych >= 'g') goto yy495;
		}
yy524:
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		YYFILL(3);
		yych = *YYCURSOR;
		if (yybm[0+yych] & 16) {
			goto yy524;
		}
		if (yych == 'i') goto yy527;
		if (yych == 'u') goto yy528;
yy526:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 16, 0, parm, parserLoc); }
yy527:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy538;
		case '3':	goto yy537;
		case '6':	goto yy536;
		case '8':	goto yy529;
		default:	goto yy495;
		}
yy528:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy533;
		case '3':	goto yy532;
		case '6':	goto yy531;
		case '8':	goto yy529;
		default:	goto yy495;
		}
yy529:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 16, 2, parm, parserLoc); }
yy531:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy534;
		goto yy495;
yy532:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy534;
		goto yy495;
yy533:
		yych = *++YYCURSOR;
		if (yych != '6') goto yy495;
yy534:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 16, 3, parm, parserLoc); }
yy536:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy534;
		goto yy495;
yy537:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy534;
		goto yy495;
yy538:
		yych = *++YYCURSOR;
		if (yych == '6') goto yy534;
		goto yy495;
yy539:
		yyaccept = 3;
		YYMARKER = ++YYCURSOR;
		YYFILL(3);
		yych = *YYCURSOR;
		if (yybm[0+yych] & 32) {
			goto yy539;
		}
		if (yych == 'i') goto yy542;
		if (yych == 'u') goto yy543;
yy541:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 2, 0, parm, parserLoc); }
yy542:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy553;
		case '3':	goto yy552;
		case '6':	goto yy551;
		case '8':	goto yy544;
		default:	goto yy495;
		}
yy543:
		yych = *++YYCURSOR;
		switch (yych) {
		case '1':	goto yy548;
		case '3':	goto yy547;
		case '6':	goto yy546;
		case '8':	goto yy544;
		default:	goto yy495;
		}
yy544:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 2, 2, parm, parserLoc); }
yy546:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy549;
		goto yy495;
yy547:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy549;
		goto yy495;
yy548:
		yych = *++YYCURSOR;
		if (yych != '6') goto yy495;
yy549:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return yoLexIntRadix(parserElem, 2, 3, parm, parserLoc); }
yy551:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy549;
		goto yy495;
yy552:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy549;
		goto yy495;
yy553:
		yych = *++YYCURSOR;
		if (yych == '6') goto yy549;
		goto yy495;
yy554:
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
yy555:
		if (yybm[0+yych] & 64) {
			goto yy554;
		}
		goto yy460;
yy556:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_AS; }
yy558:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_WHILE; }
yy563:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_GET; }
yy566:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy571;
		goto yy555;
yy567:
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'p') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LOOP; }
yy571:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LET; }
yy573:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_RETURN; }
yy579:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'd') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_VOID; }
yy583:
		yych = *++YYCURSOR;
		if (yych == 's') goto yy590;
		goto yy555;
yy584:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_EXTERN; }
yy590:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy555;
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '_') {
			if (yych <= '?') {
				if (yych <= '/') goto yy592;
				if (yych <= '9') goto yy554;
			} else {
				if (yych <= 'Z') goto yy554;
				if (yych >= '_') goto yy554;
			}
		} else {
			if (yych <= 'i') {
				if (yych <= '`') goto yy592;
				if (yych <= 'h') goto yy554;
				goto yy593;
			} else {
				if (yych <= 'z') goto yy554;
				if (yych >= 0x7F) goto yy554;
			}
		}
yy592:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_ELSE; }
yy593:
		yych = *++YYCURSOR;
		if (yych != 'f') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_ELSEIF; }
yy596:
		yych = *++YYCURSOR;
		if (yych == 'd') goto yy600;
		goto yy555;
yy597:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MUTABLE; }
yy600:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MODULE; }
yy602:
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_NULL; }
yy606:
		yych = *++YYCURSOR;
		if (yych == 'u') goto yy611;
		goto yy555;
yy607:
		yych = *++YYCURSOR;
		if (yych != 'p') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_TYPE; }
yy611:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_TRUE; }
yy614:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy637;
		goto yy555;
yy615:
		yych = *++YYCURSOR;
		if (yych == 'z') goto yy632;
		goto yy555;
yy616:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy623;
		goto yy555;
yy617:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_SWITCH; }
yy623:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy624;
		if (yych == 'u') goto yy625;
		goto yy555;
yy624:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy629;
		goto yy555;
yy625:
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_STRUCT; }
yy629:
		yych = *++YYCURSOR;
		if (yych != 'g') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_STRING; }
yy632:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'f') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_SIZEOF; }
yy637:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_SET; }
yy639:
		yych = *++YYCURSOR;
		if (yych == 'f') goto yy646;
		goto yy555;
yy640:
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'b') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy555;
yy644:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FLOAT64; }
yy646:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DEFAULT; }
yy652:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy668;
		goto yy555;
yy653:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy661;
		goto yy555;
yy654:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy659;
		goto yy555;
yy655:
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FUNC; }
yy659:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FOR; }
yy661:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '?') {
			if (yych <= '3') {
				if (yych <= '/') goto yy664;
				if (yych <= '2') goto yy554;
				goto yy665;
			} else {
				if (yych == '6') goto yy666;
				if (yych <= '9') goto yy554;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yy554;
				if (yych >= '_') goto yy554;
			} else {
				if (yych <= '`') goto yy664;
				if (yych <= 'z') goto yy554;
				if (yych >= 0x7F) goto yy554;
			}
		}
yy664:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FLOAT32; }
yy665:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy667;
		goto yy555;
yy666:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy644;
		goto yy555;
yy667:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy554;
		}
		goto yy664;
yy668:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy669;
		if (yych == 's') goto yy670;
		goto yy555;
yy669:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy673;
		goto yy555;
yy670:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FALSE; }
yy673:
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'g') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_FALLTHROUGH; }
yy681:
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '9') {
			if (yych <= '3') {
				if (yych <= '0') {
					if (yych >= '0') goto yy554;
				} else {
					if (yych <= '1') goto yy687;
					if (yych <= '2') goto yy554;
					goto yy688;
				}
			} else {
				if (yych <= '6') {
					if (yych <= '5') goto yy554;
					goto yy689;
				} else {
					if (yych == '8') goto yy685;
					goto yy554;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych >= '@') goto yy554;
				} else {
					if (yych == '_') goto yy554;
				}
			} else {
				if (yych <= 'p') {
					if (yych <= 'o') goto yy554;
					goto yy690;
				} else {
					if (yych <= 'z') goto yy554;
					if (yych >= 0x7F) goto yy554;
				}
			}
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT; }
yy685:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT8; }
yy687:
		yych = *++YYCURSOR;
		if (yych == '6') goto yy698;
		goto yy555;
yy688:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy696;
		goto yy555;
yy689:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy694;
		goto yy555;
yy690:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINTPTR; }
yy694:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT64; }
yy696:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT32; }
yy698:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT16; }
yy700:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_IF; }
yy702:
		yych = *++YYCURSOR;
		if (yych == 'p') goto yy722;
		goto yy555;
yy703:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '_') {
			if (yych <= '?') {
				if (yych <= '/') goto yy704;
				if (yych <= '9') goto yy554;
			} else {
				if (yych <= 'Z') goto yy554;
				if (yych >= '_') goto yy554;
			}
		} else {
			if (yych <= 't') {
				if (yych <= '`') goto yy704;
				if (yych <= 's') goto yy554;
				goto yy705;
			} else {
				if (yych <= 'z') goto yy554;
				if (yych >= 0x7F) goto yy554;
			}
		}
yy704:
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_IN; }
yy705:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '9') {
			if (yych <= '3') {
				if (yych <= '0') {
					if (yych >= '0') goto yy554;
				} else {
					if (yych <= '1') goto yy707;
					if (yych <= '2') goto yy554;
					goto yy708;
				}
			} else {
				if (yych <= '6') {
					if (yych <= '5') goto yy554;
					goto yy709;
				} else {
					if (yych == '8') goto yy710;
					goto yy554;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych >= '@') goto yy554;
				} else {
					if (yych == '_') goto yy554;
				}
			} else {
				if (yych <= 'p') {
					if (yych <= 'o') goto yy554;
					goto yy712;
				} else {
					if (yych <= 'z') goto yy554;
					if (yych >= 0x7F) goto yy554;
				}
			}
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INT; }
yy707:
		yych = *++YYCURSOR;
		if (yych == '6') goto yy720;
		goto yy555;
yy708:
		yych = *++YYCURSOR;
		if (yych == '2') goto yy718;
		goto yy555;
yy709:
		yych = *++YYCURSOR;
		if (yych == '4') goto yy716;
		goto yy555;
yy710:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INT8; }
yy712:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INTPTR; }
yy716:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INT64; }
yy718:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INT32; }
yy720:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INT16; }
yy722:
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_IMPORT; }
yy727:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy737;
		goto yy555;
yy728:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy733;
		goto yy555;
yy729:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT8; }
yy733:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'k') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_BREAK; }
yy737:
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_BOOL; }
yy740:
		yych = *++YYCURSOR;
		if (yych <= 'r') goto yy555;
		if (yych <= 's') goto yy768;
		if (yych <= 't') goto yy769;
		goto yy555;
yy741:
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy763;
		goto yy555;
yy742:
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy759;
		goto yy555;
yy743:
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy555;
		yych = *++YYCURSOR;
		if (yych <= 'r') goto yy555;
		if (yych <= 's') goto yy745;
		if (yych <= 't') goto yy746;
		goto yy555;
yy745:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy757;
		goto yy555;
yy746:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy748;
		if (yych != 'r') goto yy555;
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy753;
		goto yy555;
yy748:
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CONTINUE; }
yy753:
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CONTRACT; }
yy757:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CONST; }
yy759:
		yych = *++YYCURSOR;
		if (yych != 's') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 's') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CLASS; }
yy763:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy764;
		if (yych == 'r') goto yy766;
		goto yy555;
yy764:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CHAN; }
yy766:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_UINT8; }
yy768:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy773;
		goto yy555;
yy769:
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy555;
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy555;
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CATCH; }
yy773:
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 64) {
			goto yy554;
		}
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CASE; }
yy775:
		yych = *++YYCURSOR;
		goto yy457;
yy776:
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
yy777:
		if (yybm[0+yych] & 128) {
			goto yy776;
		}
		goto yy455;
yy778:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DECL_ASSIGN; }
yy780:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_EQ; }
yy782:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LE; }
yy784:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy788;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LSH; }
yy786:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CHAN_ACCESS; }
yy788:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_LSH_ASSIGN; }
yy790:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_GE; }
yy792:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy794;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_RSH; }
yy794:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_RSH_ASSIGN; }
yy796:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_XORXOR; }
yy798:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_XOR_ASSIGN; }
yy800:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_ANDAND; }
yy802:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_AND_ASSIGN; }
yy804:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_OROR; }
yy806:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_OR_ASSIGN; }
yy808:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MOD_ASSIGN; }
yy810:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ yoLexMultiLineComment(parm, parserLoc); goto restart; }
yy812:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ yoLexLineComment(parm, parserLoc); goto restart; }
yy814:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DIV_ASSIGN; }
yy816:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy820;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_POW; }
yy818:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MUL_ASSIGN; }
yy820:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_POW_ASSIGN; }
yy822:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_MINUS_ASSIGN; }
yy824:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DEC; }
yy826:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_PLUS_ASSIGN; }
yy828:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_INC; }
yy830:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '.') goto yy834;
		if (yych == '=') goto yy832;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CONCAT; }
yy832:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_CONCAT_ASSIGN; }
yy834:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_DOTDOTDOT; }
yy836:
		++YYCURSOR;
		yoLexTrackRule(parserElem, parm, parserLoc); // yyleng = YYCURSOR - yytext;
		{ return T_NE; }
	}
}

}
